### ISSUE TITLE
Make into npm package

### ISSUE THREAD

**Issue by mikefrancis** [benchmarkstudios/simple-grid#7]
Hey Pedro,

I was thinking about how we used `simple-grid` and `barebones` in the past, when `simple-grid` was integrated into `barebones`, then it was a submodule and now it's completely separate and needs to be pulled in as a separate repository.

It then occurred to me that it would be a lot easier to use both of them together if `simple-grid` was an npm package that you could `npm install --save-dev simple-grid` (or something similar). Then in the main Sass file, you can just `@import 'node_modules/simple-grid/simple-grid.scss'`.

You could even go as far as making the entire CSS framework in `barebones` an npm package that way it will keep the theme and front-end totally separate, then you can use the front-end for non-WordPress projects without having to modify it.

Just an idea any way, it's up to you guys what you do :smile:

**Comment by pdcreis** [comment]
Hey Mike,

To integrate the simple-grid in barebones we just need to run `git submodule init` and `git submodule update` after cloning the barebones repo, and the simple-grid is automatically pulled to the vendor folder.

But yeah, I agree! I think we can simplify the process of integration of both components. Sounds good your suggestion of pulling the simple-grid using npm. So in this case we could simply add it to the package.json, and when we install all the npm dependencies this would automatically be pulled (I think that's it, right?). 

But I even agree more with your second suggestion! Sometimes I download barebones just to use the scss folder. But here we would have to move it from the node_modules to the root. 

I'll have a chat with Dan and I'll give it a try!

Thank youuu!!!

**Comment by mikefrancis** [comment]
Yes! That's all how I'd see it working.

I don't think you'd need to move the scss folder into the theme root - you could just have a `styles.scss` "entry" point in the theme somewhere, then in that file you can `@import` all of your other files like so:

```
@import '../node_modules/some-package/some-package.scss`;
@import '../node_modules/barebones/barebones.scss`;
// etc
```

That way you can pick and choose other external libraries to use in your projects without having to copy them across or worry about version control. As these will have been installed via npm, they will all be kept track of in the theme's `package.json`.
